from PythonChessTest.Board_Test import *
from PythonChessTest.King_Test.ShowAvailableMovesKing_Test import *
from PythonChessTest.King_Test.MoveChessKing_Test import *
from PythonChessTest.Pawn_Test.ShowAvailableMovesPawn_Test import *
from PythonChessTest.Pawn_Test.MoveChessPawn_Test import *
from PythonChessTest.Pawn_Test.CaptureChessPawn_Test import *
from PythonChessTest.Pawn_Test.PromotePawn_Test import *
from PythonChessTest.Game_Test import *
from PythonChessTest.Queen_Test.ShowAvailableMovesQueen_Test import *